int8 command
int8 CMD_LAUNCH = 1
int8 CMD_LAND = 2
int8 CMD_ARM = 3
int8 CMD_DISARM = 4
int8 CMD_SET_STABILIZE = 5
int8 CMD_SET_ALT_HOLD = 6
int8 CMD_SET_AUTO = 7
int8 CMD_SET_LOITER = 8
int8 CMD_SET_LAND = 9
int8 RETURN_RC_CONTROL = 10
---
bool result
